// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvvtcklsmieqqfquvukv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2dnRja2xzbWllcXFmcXV2dWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Mzk3NzEsImV4cCI6MjA3MDAxNTc3MX0.wwHlL649rP3GwRXeZeyX5YY-Is3C8zz_nSc66lJhutM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});